### POST - nowe dane
POST http://localhost:3001/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="xfce4.jpeg"
Content-Type: image/jpeg

< ./xfce4.jpeg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

nazwa_albumu2
------FormBoundary1234

###
GET http://localhost:3001/api/photos HTTP/1.1

###
GET http://localhost:3001/api/photos/1 HTTP/1.1

###
DELETE http://localhost:3001/api/photos/1 HTTP/1.1

###
PATCH  http://localhost:3001/api/photos HTTP/1.1
Content-Type: application/json

{
    "id": 2
}

###
GET http://localhost:3001/api/getfile/2 HTTP/1.1
