###
GET http://localhost:3001/api/tags/raw HTTP/1.1

###
GET http://localhost:3001/api/tags HTTP/1.1

###
GET http://localhost:3001/api/tags/1 HTTP/1.1

###
POST http://localhost:3001/api/tags HTTP/1.1
Content-Type: application/json

{
    "name":"#nowytag",
    "popularity": 1000000
}

###
PATCH http://localhost:3001/api/photos/tags HTTP/1.1

{
    "imageId": 1,
    "name":"#nowytag",
    "popularity": 1000000
}

###
PATCH http://localhost:3001/api/photos/tags/multi HTTP/1.1

{
    "imageId": 1,
    "tags": [   
        {
            "name":"#nowytag1",
            "popularity": 1000000
        },
        {
            "name":"#nowytag2",
            "popularity": 10020
        }
    ]
}

###
GET http://localhost:3001/api/photos/tags/1 HTTP/1.1