POST http://localhost:3001/api/user/register HTTP/1.1
Content-Type: application/json

{
    "name":"Alfons",
    "lastName": "Eignstaing",
    "email": "fajny.mail@spoko.pl",
    "password": "Kubic@1234"
}

###
GET http://localhost:3001/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZham55Lm1haWxAc3Bva28ucGwiLCJhbnlEYXRhIjoiMTY4NDI1MDMxMTU5MiIsImlhdCI6MTY4NDI1MDMxMSwiZXhwIjoxNjg0MjUwMzcxfQ.u4QFM0tUW6mZMnJmAjIFycMnuZhtnCJopGGY4-6EQGI

###
POST http://localhost:3001/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "fajny.mail@spoko.pl",
    "password": "Kubic@1234"
}

###
GET http://localhost:3001/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZham55Lm1haWxAc3Bva28ucGwiLCJhbnlEYXRhIjoiMTY4NDQ3NzAzODI2NyIsImlhdCI6MTY4NDQ3NzAzOCwiZXhwIjoxNjg0NDgwNjM4fQ.t7Ri_LEXaXmybWXOppsQod05XrnYBKZ8CdWdDpWSm3Y

###
PATCH  http://localhost:3001/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZham55Lm1haWxAc3Bva28ucGwiLCJhbnlEYXRhIjoiMTY4NDQ3NzAzODI2NyIsImlhdCI6MTY4NDQ3NzAzOCwiZXhwIjoxNjg0NDgwNjM4fQ.t7Ri_LEXaXmybWXOppsQod05XrnYBKZ8CdWdDpWSm3Y

{
    "name": "Arnold",
    "lastName": "Dziad"
}

