### POST - nowe dane
POST http://localhost:3000/api/tasks HTTP/1.1
content-type: application/json

{    
  "a": 1,
  "b": 2
}

### GET - pobierz wszystkie dane
GET http://localhost:3000/api/tasks HTTP/1.1

### GET - pobierz jeden element wg id
GET http://localhost:3000/api/tasks/1 HTTP/1.1

### DELETE - usuń wg id
DELETE http://localhost:3000/api/tasks/1 HTTP/1.1

### PATCH - updatuj wg id
PATCH  http://localhost:3000/api/tasks HTTP/1.1
content-type: application/json

{
  "id": 10,
  "a": 111111,
  "b": 222222
}